#
# FYI: This file is replaced by a copy for deploys
# to ci, pre_production, and production.
#
<%
  port = ENV["FEDORA_PORT"] || "8983"
  host = ENV["FEDORA_HOST"] || "127.0.0.1"
%>

development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "http://#{host}:#{port}/fedora" %>
test: &TEST
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "http://#{host}:#{port}/fedora-test" %>
ci:
  <<: *TEST
  url: http://127.0.0.1:8983/fedora-test" %>
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://your.production.server:8080/fedora
cucumber:
  <<: *TEST
