name: curate_nd-ci
on:
  push:
jobs:
  test-curate_nd:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Install bundler
      run: gem install bundler -v 1.17.3

    - name: Install bundled dependencies
      run: bundle install --without headless debug

    - name: stop local  mysql
      run: sudo service mysql stop

    - name: Start CI DB & Jetty via Docker Compose
      run: docker-compose -f docker-compose-test.yml up -d

    - name: Check on our containers
      run: docker ps -a

    - name: Run CI Tests 
      env:
        RAILS_ENV: ci
      run: bundle exec rake curatend:ci_prep && bundle exec rake spec curatend:lint_erb SPEC_OPTS="--tag ~js:true"
